#!/bin/bash

## Environment
DATACENTER="us1.staging.dog"
K8_CLUSTER="gizmo.${DATACENTER}"

CLUSTER_NAMESPACE="cass-payload-versions"



kubectl config use-context $K8_CLUSTER
kubectl port-forward svc/payload-versions-dc1-3049-service 9042:9042 -n $CLUSTER_NAMESPACE