#!/bin/bash

DATABASE="dashbooks"

## Environment
DATACENTER="us1.staging.dog"
K8_CLUSTER="gizmo.${DATACENTER}"


LOGICAL_NAME="dashbooks"
CLUSTER_NAMESPACE="orgstore-${LOGICAL_NAME}"

USER="archana.asokan"


orgstore toolbox psql --database $DATABASE --database-user $USER --datacenter $DATACENTER --kubernetes-cluster $K8_CLUSTER --orgstore-cluster $LOGICAL_NAME